spring.datasource.url=jdbc:mysql://localhost:3306/flavora
spring.datasource.username=root
spring.datasource.password=Rakesh@258369

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


 \u2705 ADD THIS LINE
server.port=9091